# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: Huawei Inc.

stages:
  - compliance
  - build
  - test
  - deploy

include:
 - project: 'OSTC/infrastructure/pipelines'
   file:
    - 'dco.yaml'
    - 'reuse.yaml'
 - project: 'OSTC/OHOS/manifest'
   file: '.ostc-ci/build-generic.yaml'

dco:
  extends: .dco

reuse:
  extends: .reuse
  allow_failure: true

# Customize the .workspace job to set the path of the git repository to deviate
# from what the git-repo manifest prepares. This effectively allows testing
# incoming changes that match the repository holding this CI pipeline.
.workspace:
  variables:
    OHOS_CI_GIT_REPO_PATH: sources/poky/meta-clang
